#!/usr/bin/env bash
# A Bash Script that installs installs nginx on my Web server
# Requirements:
# Install nginx on your web-01
# server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Hello World!
# As an answer file, write a Bash script that configures a new Ubuntu machine to respect above requirements (this script will be run on the server itself)
# You can’t use systemctl for restarting nginx
# I copied this Bash script to the server using 0-transfer_file and ran it on the server
# By default, Nginx listens on port 80
#
apt-get update
apt-get -y install nginx
ufw allow "Nginx HTTP"
echo "Hello World!" > /var/www/html/index.html
service nginx start
