#!/usr/bin/env bash
# A Bash script that customs an Nginx server to have a custom 404 page that contains the string "Ceci n'est pas une page"
# Requirements:
# The page must return an HTTP 404 error code
# The page must contain the string Ceci n'est pas une page
# Using what you did with 3-redirection, write 4-not_found_page_404 so that it configures a brand new Ubuntu machine to the requirements asked in this task
# I copied this Bash script to the server using 0-transfer_file and ran it on the server
# By default, Nginx listens on port 80
#
# First install the Nginx server
sudo apt update
sudo apt-get install -y nginx 
echo "Hello World!" > index.html
sudo mv index.html /var/www/html
#
# Creates a custom 404.html file
echo "Ceci n'est pas une page" > /var/www/html/404.html
#
# Configuring the server to redirect the 404.html page
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location = /404.html{
        internal;
    }
}" > /etc/nginx/sites-available/default
#
# Restarting the nginx service
sudo service nginx restart
