#!/usr/bin/env bash
#
# A Bash script that transfers a file from our client to a server:
# Requirements:
# Accepts 4 parameters
# The path to the file to be transferred
# The IP of the server we want to transfer the file to
# The username scp connects with
# The path to the SSH private key that scp uses
# Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY if less than 3 parameters passed
# scp must transfer the file to the user home directory ~/
# Strict host key checking must be disabled when using scp
#
# Declaration of variables
localFile=$1 # Path to local file
ipAddress=$2 # IP address
userName=$3 # Username on server
pathToSSHPrivateKey=$4 # Path to private SSH key
#
# Check if command line arguments are less than 3
# $# is the length of command line arguments
if [ $# -lt 3 ];
then
	echo "Usage: execute_task1_on_my_server PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$pathToSSHPrivateKey" "$localFile" "$userName"@"$ipAddress":~/
fi
