#!/usr/bin/env bash
# A Bash script that:
# - Configure HAProxy to send traffic to web-01 and web-02
# - Distribute requests using a roundrobin algorithm
# - Make sure that HAProxy can be managed via an init script
# Installing and configuring HAproxy on my lb-01 server
sudo apt-get -y update
sudo apt-get -y install haproxy

# Editing the HAProxy config file
echo "
frontend  dohoudaniel-frontend
        bind *:80
        mode http
        default_backend dohoudaniel-backend
backend dohoudaniel-backend
        balance roundrobin
        server 125427-web-01 18.210.18.189:80 check
        server 125427-web-02 100.26.120.45:80 check
" >> /etc/haproxy/haproxy.cfg

# Enabling the HAProxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
# Restarting the HAProxy service
sudo service haproxy restart
