#!/usr/bin/env bash
# A Bash script that displays To infinity and beyond indefinitely.
# Requirements:
# In between each iteration of the loop, add a sleep 2
myString="To infinity and beyond"
while true
do
	echo "$myString"
	sleep 2
	#
	# Handling SIGTERM signals through a function
	handle_sigterm() {
		echo "I am invincible!!!"
	}
	trap handle_sigterm SIGTERM
done
