#!/usr/bin/env bash
# A Bash script that sends a SIGTERM signal to the 7-highlander process
#
# Storing the PID of the 7-highlander process in a variable
pidOfScript=$(ps -u | grep "bash ./7-highlander" | grep -v grep | awk '{print $2}')
kill -9 "$pidOfScript"
