#!/usr/bin/env bash
# A Bash script that sends a SIGTERM signal to the 7-highlander process
#
# Storing the PID of the 7-highlander process in a variable
pidOfScript=$(pgrep -f "7-highlander")
kill -9 "$pidOfScript"
