#!/usr/bin/env bash
# A Bash script that displays To infinity and beyond indefinitely.
# Requirements:
# In between each iteration of the loop, add a sleep 2
myString="I am alive!"
while true
do
	echo "$myString" >> /tmp/my_process
	sleep 2
done
