#!/usr/bin/env bash
# This script displays "Best School" 10 times
# Initializing a variable i
i=0
# Using a whhile loop to increment i to print "Best School"
for ((i = 0; i < 10; i++))
do
	echo "Best School"
done
