#!/usr/bin/env bash
# A script that prints "Best School" using a while loop
# Initializing a variable i
i=0
# Using a whhile loop to increment i to print "Best School"
while [ $i -lt 10 ]
do
	echo "Best School"
	((i++))
done
