#!/usr/bin/env bash
# A script that prints "Best School" using a while loop
# Initializing a variable i
i=0
# Using a whhile loop to increment i to print "Best School"
while [ $i -le 10 ]
do
	if [ $i -eq 9 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	# Increment our variable
	((i++))
done
