#!/usr/bin/env bash
# A Bash script that dispalays 1 to 20 and
#+ displays 4 and then bad luck from China for the 4th loop iteration
#+ displays 9 and then bad luck from Japan for the 9th loop iteration
i=1
j=0

while [ $j -lt 20 ]
do
        case "$i" in
        4)
                echo "$i"
                echo "bad luck from China"
                ;;
        9)
                echo "i"
                echo "bad luck from Japan"
                ;;
        17)
                echo "$i"
                echo "bad luck from Italy"
                ;;
        *)
                echo "$i"
                ;;

        esac

        i=$((i + 1))
        j=$((j + 1))
done
