#!/usr/bin/env bash
# A Bash script that loops from 1 to 10 and:
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations
#
# Declare a variable
i=1
# Using a whhile loop to increment i to print "Best School"
while [ $i -le 20 ]
do
	if [ $i -eq 4 ]
	then
		echo "$i"
		echo "bad luck from China"
	elif [ $i -eq 9 ]
	then
		echo "$i"
		echo "bad luck from Japan"
	elif [ $i -eq 17 ]
	then
		echo "$i"
		echo "bad luck from Italy"
	else
		echo "$i"
	fi
	# Increment our variable
	((i++))
done
