#!/usr/bin/env bash
# A Bash script that loops from 1 to 10 and:
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations
#
# Declare two variables
i=0
j=1
# Using a whhile loop to increment i to print "Best School"
while [ $i -lt 20 ]
do
	echo "$i"
	case $j in
		4)
			# echo "$j"
			echo "bad luck from China"
			;;
		9)
			# echo "$j"
			echo "bad luck from China"
			;;
		17)
			# echo "$j"
			echo "bad luck from Italy"
			;;
		# *)
			# echo "$i"
	esac
	# Increment the variable
	((i++))
	((j++))
done
