#!/usr/bin/env bash
# A Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# displays minutes from 1 to 59
# Requirements:
# You must use the while loop (for and until are forbidden)
hour=0
# minuite=1
# Using a whhile loop to increment i to print "Best School"
while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	minuite=1
	while [ $minuite -le 59 ]
	do
		 echo "$minuite"
		 ((minuite++))
	done
	((hour++))
done
