#!/usr/bin/env bash
# Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed (refer to the example)
# Requirements:
# You must use the for loop (while and until are forbidden)
# Do not display hidden files
#
# Store the ls command output inside a variabele
myList=$(ls)
# Looping through the myList variable to truncate output before the dash
for i in $myList
do
	echo "$i" | cut -d '-' -f2
done
