#!/usr/bin/env bash
# A  Bash script that displays all active IPv4 IPs on the machine it’s executed on.
# Example:
# sylvain@ubuntu$ ./1-show_attached_IPs | cat -e
# 10.0.2.15$
# 127.0.0.1$
# sylvain@ubuntu$
# Obviously, the IPs displayed may be different depending on which machine you are running the script on.
# Note that we can see our localhost IP :)
#
ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | cut -b 6-
