#!/usr/bin/env bash
# A Bash Script that fixes a Docker container so that Nginx is running as the Nginx user. Nginx must be running as nginx user
sed -i "s/#user www-data/user nginx/g" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
