#!/usr/bin/env bash
# A Bash script that uses ssh to connect
# to my server using my private key ~/.ssh/school
# with the user 'ubuntu'
# Only use ssh single-character flags
# -l must not be used
# You do not need to handle the case of a private key protected by a passphrase
ssh ubuntu@54.209.110.94 -i ~/.ssh/school
#
# user: ubuntu
# -i : This single character flag specifies the path to the private key file to be used for the connection.
