#!/usr/bin/env bash
# A Bash script that uses ssh to connect to your server using the private key ~/.ssh/school with the user ubuntu.
# Requirements:
# Only use ssh single-character flags
# -l must not be used
# You do not need to handle the case of a private key protected by a passphrase
ssh ubuntu@18.210.18.189 -i ~/.ssh/school
# -i : This single character flag specifies the path to the private key file to be used for the connection.
